// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.CofeeShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenningHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CofeeShops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bismarck, North Dakota",
                            Name = "The Mighty Missouri Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bismarck, North Dakota",
                            Name = "Mighty Missouri Coffee Company"
                        },
                        new
                        {
                            Id = 3,
                            Address = "St. Paul, Minnesota",
                            Name = "Spyhouse Coffee"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Las Vegas, Nevada",
                            Name = "Sambalatte"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Columbus, Ohio ",
                            Name = "Fox in the Snow"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Salt Lake City, Utah",
                            Name = "Three Pines Coffee"
                        },
                        new
                        {
                            Id = 7,
                            Address = "NYC, New York",
                            Name = "Abraco"
                        },
                        new
                        {
                            Id = 8,
                            Address = "San Francisco ",
                            Name = "Sightglass Coffee"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Naples, Florida",
                            Name = "Narrative Coffee Roasters"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Honolulu, Hawaii",
                            Name = "Morning Glass"
                        },
                        new
                        {
                            Id = 11,
                            Address = "St. Cloud, Minnesota",
                            Name = "Kinder Coffee Lab"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Chicago, Illinois",
                            Name = "Sip & Savor"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Waynesville, North Carolina",
                            Name = "Orchard Coffee"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Harrison, New Jersey",
                            Name = "Coperaco"
                        },
                        new
                        {
                            Id = 15,
                            Address = "San Diego, California",
                            Name = "Communal Coffee"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Cleveland, Ohio",
                            Name = "Rising Star Coffee Roasters"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
